/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialPackagesIndexRouteImport } from './routes/special-packages.index'
import { Route as SpecialPackagesSlugRouteImport } from './routes/special-packages.$slug'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialPackagesIndexRoute = SpecialPackagesIndexRouteImport.update({
  id: '/special-packages/',
  path: '/special-packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialPackagesSlugRoute = SpecialPackagesSlugRouteImport.update({
  id: '/special-packages/$slug',
  path: '/special-packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/special-packages/$slug': typeof SpecialPackagesSlugRoute
  '/special-packages/': typeof SpecialPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/special-packages/$slug': typeof SpecialPackagesSlugRoute
  '/special-packages': typeof SpecialPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/special-packages/$slug': typeof SpecialPackagesSlugRoute
  '/special-packages/': typeof SpecialPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/packages'
    | '/privacy-policy'
    | '/special-packages/$slug'
    | '/special-packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/packages'
    | '/privacy-policy'
    | '/special-packages/$slug'
    | '/special-packages'
  id:
    | '__root__'
    | '/'
    | '/packages'
    | '/privacy-policy'
    | '/special-packages/$slug'
    | '/special-packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SpecialPackagesSlugRoute: typeof SpecialPackagesSlugRoute
  SpecialPackagesIndexRoute: typeof SpecialPackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-packages/': {
      id: '/special-packages/'
      path: '/special-packages'
      fullPath: '/special-packages/'
      preLoaderRoute: typeof SpecialPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-packages/$slug': {
      id: '/special-packages/$slug'
      path: '/special-packages/$slug'
      fullPath: '/special-packages/$slug'
      preLoaderRoute: typeof SpecialPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SpecialPackagesSlugRoute: SpecialPackagesSlugRoute,
  SpecialPackagesIndexRoute: SpecialPackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
